### ISSUE TITLE
Source

### ISSUE THREAD

**Issue by nuhnicek** [WieszakWare/Hackord#8]
Can you put source open so we can tell that it is not virus?

**Comment by De3asz** [comment]
Hello, this is not virus

**Comment by music-cat-bread** [comment]
@nuhnicek Hello.

So let me explain.
In the past (Hackord V1 and prior) was open source, but because of potentials legal complications with publishing and maintaining such source code @WieszakWare has decided to take closed source with the release of V2.
We understand that many user will be concerned, but we haven't tried to obfuscate it nor put any vm locks so if you want you can spin up one yourself and test it from there.

And don't think bad about me.
Personally I would love to put this project open source, but there is just one thing more.
Tools like that are really look after in dark web as many people can make fat stacks of money from tools like that, and because of that those tools are rarely available to public. And those which are most of the time are just crappy, because there are made in free time and trying to make publicly profit out of those tools are going to quickly get us in trouble.

As of right now I don't have much power as I haven't developed Hackord in ages.
I only have helped a little bit at the start with private betas and general "how can we achieve this".
For now I am just right hand and help from time to time.
But @WieszakWare not I have a lot of time, because of school.
And even then we can't dedicate our lives to this project as it's just kinda for fun.
I personally never taken this project for serious, but now I see that @WieszakWare have taken it seriously.
And still after months, some smaller rewrites, and one major one.... this projects has hone nowhere.
Code base is the most hot garbage that I could have ever imagined.
And if I would do it for serious I would just scrap what has been made for now and start from the beginning and release only when I am happy with initial code base, and also try to somehow do it without technically breaking any rules.

So I hope that explains everything and I am willing to hear back from you what you think now.
Have a nice day (or night in my case)!
